src/ResponseMixin.php

Adds optional ability to check for correct response by status code when using `->assertValidResponse()`.
Resolves https://github.com/spurjobs/spectator/issues/2

Add ability to check status code as well

---

src/Middleware.php
src/Validation/ResponseValidator.php
tests/Fixtures/Test.v1.json
tests/ResponseValidatorTest.php

A crude proposal to provide more context information in case no `operationId` is set. Providing access to the full request object in the response validation would also be an option.
```diff
- does not match the spec: [ type: {\"expected\":\"string\",\"used\":\"null\"} ]
+path-without-operationId does not match the spec: [ type: {\"expected\":\"string\",\"used\":\"null\"} ]
```

Fall back to request URI if operationId not defined

---

src/Validation/ResponseValidator.php
tests/ResponseValidatorTest.php

Proposal to include the `dataPointer` of the offending field in json response.
```diff
-get-users does not match the spec: [ type: {"expected":"number","used":"string"} ]
+get-users json response field 0.email does not match the spec: [ format: {"type":"string","format":"email"} ]
```

Include offending data pointer in response validation error

---

.github/workflows/php.yml
composer.json
src/ResponseMixin.php

This PR adds php 8 in composer.json
Tests are now run on all supported php versions and for all supported laravel version
orchestra/testbench version was bumped with documented versions (https://github.com/orchestral/testbench)

Add support and testing for PHP8

---

src/Middleware.php
tests/Fixtures/Test.v2.json
tests/ResponseValidatorTest.php

Allow `path_prefix` to contain slashes, e.g. `api/v2`.

Fix path_prefix to work with multi-segment urls

---

composer.json

Version 0.6.3 included a rename of the service provider from `src/ServiceProvider.php` to `src/SpectatorServiceProvider.php` as can be seen here: https://github.com/hotmeteor/spectator/compare/v0.6.2...v0.6.3
This PR fixes the issue that the namespace `Spectator` was not added correctly to the `composer.json` file hence causing errors when installing in a Laravel app:
```sh
composer require hotmeteor/spectator --dev   
Using version ^0.6.3 for hotmeteor/spectator
./composer.json has been updated
Running composer update hotmeteor/spectator
Loading composer repositories with package information
Updating dependencies
Lock file operations: 4 installs, 0 updates, 0 removals
- Locking cebe/php-openapi (1.4.2)
- Locking hotmeteor/spectator (v0.6.3)
- Locking justinrainbow/json-schema (5.2.10)
- …
```

Bugfix: Missing namespace for service provider

---

composer.json
phpunit.xml
src/Assertions.php
tests/AssertionsTest.php

This updates the way that failing tests display the line where it's failing. Before, it would refer to the line in the `Assertions` class, which isn't very helpful. Now it will point to the line in your actual test class.

Better error reporting

---

src/Validation/ResponseValidator.php
tests/Fixtures/Nullable.3.0.json
tests/Fixtures/Nullable.3.1.json
tests/ResponseValidatorTest.php

I tried this package out in a test suite with OpenAPI v3.0.x that has a lot of responses with objects that have nullable properties.
I discovered that the schema is not updated to the JSON-schema array format for those properties so the assertions are failing.
This PR adds support to validate a schema like:
```
"schema": {
"type": "object",
"properties": {
"key": {
"nested_key": {
"type": "object",
"properties": {
"nullable_key": {
"nullable": true,  <--- This was not checked before
"type": "string"
}
}
}  
}
}
```

Add support for object properties that have nullable properties

---

config/spectator.php
src/RequestFactory.php

We are currently using the `remote` option to download the OpenAPI contract file from a remote repo.  However, since including this in our deploy pipeline, we have discovered the Github Raw Access Token is only valid for 7 days.  This means, we must generate a new one and update the `env` file for each deploy.
This PR adds a method that supports the `github` option in the Spectator config file.  The token you need is a Github Personal Access Token (valid for 1 year and longer if you use it regularly).  Instructions for creating that are here (https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token)
❕ It is important to note that for the config file option `SPEC_GITHUB_PATH`, you must include the branch.  
Ex: `'base_path' => env('SPEC_GITHUB_PATH', …

:sparkles: allow github via personal access token

---

src/Validation/ResponseValidator.php
tests/Fixtures/Nullable.3.0.json
tests/Fixtures/Nullable.3.1.json
tests/ResponseValidatorTest.php

In a previous PR (#24) I did not take into account the case an array of objects is defined in the schema.
When those objects contain a nullable property the assertions are failing too because the properties are not converted to the JSON-schema array format.
This PR adds support to validate a schema like:
````
"schema": {
"type": "object",
"properties": {
"key": {
"nested_key": {
"type": "array", <--- For an array
"items": {
"type": "object", <--- of objects
"properties": {
"nullable_key": {
"nullable": true,  <--- this was not checked before
"type": "string"
}
}
}
}  
}
}

Add support for schema that has an array of objects with nullable properties

---

phpunit.xml
src/Assertions.php
src/Concerns/HasExpectations.php
src/Middleware.php
tests/Fixtures/Malformed.v1.yaml
tests/ResponseValidatorTest.php

This resolves an issue where exceptions for invalid spec files are not providing clear error messaging.
Resolves https://github.com/hotmeteor/spectator/issues/29

#29 Report on invalid spec files

---

README.md
src/Middleware.php
tests/ResponseValidatorTest.php

This PR will introduce the ability to have a full stack trace output when exception handling is disabled.
When running tests it's nicer to have the full output when an uncaught exception occurs in the codebase for debugging.
Exceptions related to invalid spec and such remain unchanged and are formatted with a useful message.
Resolves: #32

#32 Output full exception stack trace when exception handling is disabled in a test

---

src/Concerns/HasExpectations.php
src/Middleware.php
tests/AssertionsTest.php
tests/Fixtures/Test.v1.json

Renames spec error key as to not overwrite Laravel errors.
Refs https://github.com/hotmeteor/spectator/pull/49

#49 Allow for Laravel validation to pass through

---

src/Concerns/HasExpectations.php

Fixes deprecation 
```
PHP Deprecated:  trim(): Passing null to parameter #1 ($string) of type string is deprecated
```
If `message` is not found in `$contents`, `Arr::get($contents, 'message')` returns `null`.

Fix php8.1 deprecation warning

---

src/Validation/RequestValidator.php
tests/Fixtures/Test.v1.json
tests/RequestValidatorTest.php

Hello,
this PR should fix #87 . 
So the parameters should be casted to their expected type.
The alternative would be to check the types before with i.e. is_numeric. But then it would be a bigger if/else block.
But if you like it better I can change that.

Parameter type check and casting

---

src/Exceptions/SchemaValidationException.php

This function causes a `TypeError` on return when neither conditions is true.

Avoid TypeError when `formatSchema` function does not return array

---

src/Validation/RequestValidator.php
tests/Fixtures/BinaryString.v1.json
tests/RequestValidatorTest.php

This PR allows to test requests using `multipart/form-data`.
This can be handy as  `multipart/form-data` requests can have files attached.
In OpenApi, a file is defined as `string` with `binary` format

Add support for binary string in form data

---

.github/workflows/php.yml
composer.json
src/SpectatorServiceProvider.php

`cebe/php-openapi` just dropped support for `symfony/yaml:^6.0` which allows us to bring support for Laravel 9.
I dropped support for Laravel 7 which is end of life.
I also added tests under PHP 8.1

Add Laravel 9 support, drop Laravel 7 support

---

src/Validation/RequestValidator.php
tests/Fixtures/BinaryString.v1.json
tests/RequestValidatorTest.php

This PR fixes 2 bugs of #82 
Firstly, it fixes `UploadedFile` transformation  to string when they are deep in the request.
For exemple 
```php
[
'picture' => UploadedFile::fake()->image('test.jpg'),
'files' => [
['name' => 'test.jpg', 'file' => UploadedFile::fake()->image('test.jpg')],
['name' => 'test.jpg', 'file' => UploadedFile::fake()->image('test.jpg')],
],
'resume' => [
'name' => 'test.pdf',
'file' => UploadedFile::fake()->create('test.pdf'),
]
],
```
Secondly, it does not cast empty arrays to object when the array is empty.
In
```php
[
'picture' => UploadedFile::fake()->image('test.jpg'),
'files' => [],
'resume' => [
'name' => 'test.pdf',
'file' => UploadedFile::fake()->create('test.pdf'),
]
]
```
`files` must stay an array.

Fix parse body schema

---

src/Middleware.php

* `$path` param had missing type. The library supports at least PHP 7.4, so `string` type declaration can be added there.
* Remove redundant doBlock (as we now have the them in the function signature).
Hope it helps @hotmeteor! 🙂

Add type hinting to `$path` param

---

src/RequestFactory.php

Parsing the same specifications over and over again is a waste of CPU, time and network (remote or github sources)
Specs are simple cached in a hashmap in RequestFactory.
Let me know what you think - THX a lot!

feat: cache parsed OpenAPI specifications

---

src/Exceptions/SchemaValidationException.php

This PR fixes the exception output when the `array_filter(...)` method returns an array with keys like this:
```php
$polymorphic_keys = [
2 => 'allOf',
]
```
When that happens the next lines assume a key `0` to be present. Without resetting the keys the exception output cannot be formatted properly to a readable message regarding the schema validation itself.
Not entirely sure which OpenAPI structure exactly is triggering this behaviour in the project I'm working on.
Anyway I'm pretty convinced this could happen to others too. 🤷‍♂️

Reset array keys when formatting schema exception

---

_ide_helpers.php
src/Assertions.php
src/Concerns/HasExpectations.php
src/Exceptions/MalformedSpecException.php
src/Middleware.php
src/RequestFactory.php
src/Spectator.php
src/SpectatorServiceProvider.php
src/Validation/RequestValidator.php
tests/RequestValidatorTest.php
tests/ResponseValidatorTest.php

This change updates Spectator so that only validation that is specified is run. 
For example, this will only run request validation and not response validation:
```php
$this->getJson("/users")
->assertValidRequest();
```
Previously, if the response was invalid it would have thrown an error, but with the update this is no longer the case.

Skip request validation

---

src/Validation/RequestValidator.php

This PR should resolve #115 that @philsturgeon reported.
Another option is that we could just always use the `originalParameters()` method.

Support route model binding

---

src/Middleware.php
tests/MiddlewareTest.php

A bug was introduced in #110 which results in requests being processed twice if a spec file is set.
This happens because the early return was removed, and we subsequently call `$next($request)` twice in the middleware: once at the top of the `handle()` method; and once within the `validate()` method. 
The "correct" code isn't easy on the eye—which may be why the change was made in the first place—but it gets the job done. 
I've included a pretty crude test that demonstrates the issue. I wasn't too sure where to stick it, so if you want it to go somewhere else, let me know.

Requests are processed twice

---

src/Validation/RequestValidator.php
tests/Fixtures/Test.v1.json
tests/RequestValidatorTest.php

Nested query parameters such as `?filter[groupId]` always return null during the validation. 
This is due to `$this->request->query->has` being a pretty simple Symfony implementation (as documented https://github.com/laravel/framework/issues/33376) 
This adds some support to getting these nested query parameters in the recommended way from the query string. 
Fixes #130

Handle validation of nested query parameters e.g. ?filter[groupId]=

---

config/spectator.php
src/SpectatorServiceProvider.php

In our company's case, not all endpoints are under the api group. We would like to be able to change which group the middleware should be prepended to.

Add ability to choose which groups the middleware should be prepended to

---

src/Assertions.php
tests/AssertionsTest.php

This assertion is a convenient way to only check whether an endpoint is in the spec or not.
Concrete use case in one of my projects:
Iteration over all endpoints in API and check for every one of them whether they are present in the specification.
When adding these tests in the CI pipeline I can make sure that new endpoints also find their way into the specification.
Why can't I just use `assertInvalidRequest`?
Because when automatically iterating over endpoints I don't have request bodies to append and so the assertion complains about this first. I just want to know about the `InvalidPathException`.
Hope this finds the way into the codebase, otherwise I would have to find a way to extend the package.

Add assertPathExists assertion

---

src/Validation/RequestValidator.php
tests/Fixtures/CommaSeparatedString.v1.json
tests/RequestValidatorTest.php

Wasn't able to assert for valid comma separated values in query parameters e.g. `?include=foo,bar` as the value passed to the JSON schema package was still a string and not exploded.
When looking online about how people define comma separated values in query params this StackOverflow seems to be the agreed way (https://stackoverflow.com/a/66829618).
This PR just adds a little piece of logic to explode the value by comma if the property `explode` is false in the parameter.

Allow comma separated values in the query parameters

---

src/Middleware.php
tests/AssertionsTest.php

This PR fixes https://github.com/hotmeteor/spectator/issues/136
Problem comes from the fact that in the test suite, we are using Laravel's exception handler wich will hide some issues. If in their projet the developer uses `withoutExceptionHandling`, they can face Spectator bug (in this case returning an undefined variable).
I decided to fix this issue extracting PathItem resolution from actual request/response validation.
I would also suggest to run the entire test suite without exception handling (except required ones like ValidationException or HttpException) in order to prevent such issues to be hidden again. I can send a follow-up PR if you want.
Finally, not sur if this PR should be sent to master or develop branch. @hotmeteor please tell me if I should send it to develop, I will …

Fix undefined variable $response in Middleware

---

.github/workflows/tests.yml

This PR adds test execution for supported version of Laravel and PHP

Run tests on Laravel 10 and PHP 8.2/8.3

---

.github/workflows/tests.yml
composer.json

This starts the V2 track.
- Forces support for PHP 8.1+
- Forces support for Laravel 10+
- Updates dependencies accordingly.

PHP 8.1+, Laravel 10+

---

.github/workflows/tests.yml
.gitignore
composer.json
phpunit.xml
tests/RequestValidatorTest.php
tests/ResponseValidatorTest.php

Fix deprecations and update test script to get collision printer.
The vendor cache was dropped in order to always get fresh dependencies. On the first attempt, PHPUnit 9 was installed from the cache

Fix PHPUnit deprecations

---

src/Assertions.php
src/Middleware.php
src/Validation/ResponseValidator.php
tests/AssertionsTest.php
tests/MiddlewareTest.php
tests/RequestValidatorTest.php
tests/ResponseValidatorTest.php
tests/TestCase.php

This PR improves exception handling int spectator code base, especially in the tests.
All decisions I made can be discussed and revert as needed
What is done and why :
- Tests are now run `withoutExceptionHandling` which allows us to be informed of internal issues during the request, especially during request and response validation in the middleware. Without that, any error occurring there will be catched by the exception handler and transformed to a 500 response. The error can be hidden if the assertion made is an `assertInvalidResponse` for example. The tests requiring Laravel to handle some exceptions (ValidationException for example) explicitly exclude the exception during setup.
- InvalidPathException, MalformedSpecException, MissingSpecException, TypeErrorException, …

Better exception handling

---

src/Validation/RequestValidator.php
tests/Fixtures/Enum.yml
tests/RequestValidatorTest.php

This PR fixes the validation when backed enum is substituted in the controller.
The value is used for validation.

Support substituted backed enum in path

---

src/Validation/AbstractValidator.php
tests/Fixtures/Arrays.v1.yaml
tests/ResponseValidatorTest.php

In some cases, we try to filter properties of something which does not have any.
This PR fixes it, allowing to define and validate json responses like 
```json
{
"data": ["foo", "bar", "baz"]
}
```

Fix filterProperties when data does not contain properties

---

src/Validation/ResponseValidator.php
tests/ResponseValidatorTest.php

Add support for streamed response

---

src/Validation/AbstractValidator.php
tests/Fixtures/Dictionary.v1.yml
tests/ResponseValidatorTest.php

Dictionaries are objects in which the keys are not known but we can still validate the format of the values.
For example : 
```json
{
"data": {
"2024-01-27": 6,
"2024-01-28": 7
}
}
```
Before this fix, we had the error 
```
ErrorException: Undefined property: stdClass::$properties
/spectator/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:255
/spectator/src/Validation/AbstractValidator.php:72
/spectator/src/Validation/AbstractValidator.php:114
....
```
Fixes #143 
Fixes #167

Add support for dictionaries

---

.github/workflows/tests.yml
composer.json

Add Laravel 11 support
~Currently stuck as https://github.com/cebe/php-openapi does not support Symfony 7 yet~
cebe/php-openapi is currently inactive and an active fork appeared with Symfony 7 support : [DEVizzent/cebe-php-openapi](https://github.com/DEVizzent/cebe-php-openapi)
It is used by [thephpleague/openapi-psr7-validator](https://github.com/thephpleague/openapi-psr7-validator/blob/master/composer.json) and is a drop-in replacement for original package. I think it is safe to switch to this one.

Laravel 11 support

---

src/Validation/ResponseValidator.php
tests/Fixtures/EmptyResponse.yml
tests/ResponseValidatorTest.php

From now, a non empty response body will be considered invalid against a specification not defining a response content
Fixes #165

Expected empty response body

---

phpstan-baseline.neon
src/Assertions.php
src/Concerns/HasExpectations.php
src/Validation/RequestValidator.php
tests/Fixtures/AllOf.v1.yml
tests/Fixtures/Enum.yml
tests/RequestValidatorTest.php
tests/ResponseValidatorTest.php

Currently, passing `null` to `expectsTrue` passes but I think it is an error.
Indeed, if no exception was raised, `expectsTrue` will pass and a valid implementation can execute this test without failing 
```php
$this->getJson('/api/path')
->assertValidRequest()
->assertInvalidRequest()
->assertValidResponse()
->assertInvalidResponse();
```
I think that a request cannot be both valid and invalid.
This behavior caused false-positive in the tests. I fixed them

Expects true fails if the throwable is null

---

src/Assertions.php
tests/AssertionsTest.php
tests/ResponseValidatorTest.php

Http code assertion has more priority than schema validation when given to `assertValidResponse` and `assertInvalidResponse`.
I also simplify the implementation using Laravel built-in assertion.
Fixes #121

Give Http Code assertion more priority in response assertion

---

src/Validation/RequestValidator.php
tests/Fixtures/Arrays.v1.yml
tests/RequestValidatorTest.php

Fixes a bug introduced in #184

Query param can be an array

---

src/Middleware.php
src/Validation/RequestValidator.php
tests/Fixtures/Test.v1.json
tests/RequestValidatorTest.php

Before, having an openapi route like 
```json
"/users/{id}": {
"parameters": [
{
"schema": {
"type": "string"
},
"name": "id",
"in": "path",
"required": true
}
],
...
```
and a route declaration like 
```php
Route::get('users/{user}', ...);
```
was not possible because parameter names between the specification was used to get the parameter value in the Laravel world.
This PR adds a 'translation' step where we translate `id` into `user` (in this example).
I also changed the way that bindings are tested, in order to properly cover the test cases. `SubstituteBindings` middleware was missing.
Fixes #140

Remove binding between path parameter in openapi and Laravel route declaration

---

src/Validation/RequestValidator.php
tests/Fixtures/Arrays.v1.yml
tests/RequestValidatorTest.php

Fixes #187 
Array query parameters containing objects are not correctly validated because the validator requires the objects to be actual objects and not associative arrays.
The parameter value is now correctly casted.
I also needed to improve parameter casting in order to recursively cast the parameter (in case of objects and arrays). It is not perfect but it's better than before. We could improve it if needed in the future.

Improve validation and casting of request parameters

---

src/Validation/ResponseValidator.php
tests/Fixtures/ContentType.yml
tests/ResponseValidatorTest.php

The specification allows to define responses with placeholders : 
```yml
paths:
/info/logo:
get:
responses:
'200':           # Response
description: OK
content:       # Response body
image/*:     # Media type
schema: 
type: string
format: binary
```
https://swagger.io/docs/specification/media-types/
which is currently not possible.
This PR adds the support of that.
It also fixes a bug where a response having a content type like `application/json; charset=UTF-8` would not match the openapi 
```
ErrorException: Response did not match any specified content type.
Expected: application/json
Actual: application/json; charset=utf-8
```

Support charset and placeholder media types

---

.github/FUNDING.yml
README.md
UPGRADE.md
composer.json

Adds a composer alias for v2 and upgrade guide.
It might need to be completed

Prepare v2

---

_ide_helpers.php

This pull request fixes 3 issues with `_ide_helpers.php`:
- `skipRequestValidation()` doesn't exist
- `assertPathExists()` was missing
- Replacing `static` by `$this` helps IDE autocomplete ([this general problem is better described there](https://youtrack.jetbrains.com/issue/WI-26710/Type-Inference-static-method-doc-type-doesnt-work))

fix: Update _ide_helpers.php

---

src/Middleware.php
tests/Fixtures/Test.v3.yaml
tests/RequestValidatorTest.php

* Add regex pattern match against the requested url path
This issue came from having static URLs in the API documentation pointing to dynamic URL in my project. 
```
/cars/electric
/cars/ice
```
```
Route::patch('/cars/{name}', function ($name) {
return [
'name' => $name,
];
});
```
Before this change it will also match with the last defined route in the API documentation, which meant that if the request data was different then the request openAPI validation will fail.
This change will use the route binding regex and the actual request path to find the correct path. Now it will only match the exact match routes if found.

Add regex pattern match against the requested url path (#1)

---

src/Validation/RequestValidator.php
tests/Fixtures/EmptyRequestBodyAsArray.yml
tests/Fixtures/EmptyRequestBodyAsObject.yml
tests/RequestValidatorTest.php

If I execute an API call without a request body
```php
$this->patchJson('/pets')->assertValidRequest();
```
and my OpenAPI file says the request can contain an object (none of the properties are required),
```yaml
paths:
/pets:
patch:
requestBody:
content:
application/json:
schema:
type: object
properties: # none of the properties are required
name:
type: string
```
then I currently get the following error: 
```
The data (array) must match the type: object
object++ <== The data (array) must match the type: object
name: string
```
This PR fixes that. If the OpenAPI file says that an object is expected, then the empty array is converted to an empty object.

Convert empty request body to object if an object is expected by OpenAPI definition

---

src/Validation/RequestValidator.php
tests/Fixtures/Boolean.v1.json
tests/RequestValidatorTest.php

This PR fixes two issues related to request validation.
- If a parameter is not null but "falsey" such as `0` the parameter it is not validated
this PR corrects this and updates the tests
- It is currently not possible to validate "boolean" type parameters as the assertion will always fail since the string type value from the request parameter is not cast to boolean. `The data (string) must match the type: boolean`
This PR casts `true` and `false` string values only to the appropriate boolean, and adds test coverage

Fix: boolean casting
